language: node_js
sudo: false
before_install: npm install -g grunt-cli bower
install: npm install && bower install
script: grunt build:dist
cache:
  directories:
  - ".divshot-cache"
  - node_modules
  - app/bower_components
deploy:
  provider: divshot
  environment:
    master: development
    staging: staging
    production: production
  skip_cleanup: true
  api_key:
    secure: BuUclicBTqmyiEOLkZ8sEuZxOdv9W5Zf3dKHQJFeeXIvwBB7XaRjS5QOw6JERt4ifF4etRxKFpTaw9KFiXGBMJJ2eVxNSVK836Uc8DFmmt8W3MpO8s3iqxMlAEZZrKO7Dmv++LZMf8Luk1/882ENlL4rllwXSsstHfvMuUdx9rA=
